---
# tasks file for user_data
- name: Configure jenkins repo
  get_url:
    url: http://pkg.jenkins.io/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins.io.key

- name: Install latest version of Java
  yum:
    name: java
    state: latest

- name: Install the latest version of Jenkins
  yum:
    name: jenkins
    state: latest

- name: Make sure Jenkins service is running
  systemd:
    state: started
    name: jenkins

- name: shell command
  shell: rm -rf /var/lib/jenkins/*

- name: Configure jenkins repo
  get_url:
    url: https://s3-us-west-2.amazonaws.com/jenkins-newer/jenkins.tar
    dest: /var/lib/jenkins/

- name: shell command
  shell: /usr/bin/tar -xf jenkins.tar -C /var/lib/jenkins/

- name: Make sure Jenkins service is running
  systemd:
    state: started
    name: jenkins
    enabled: yes
