---
# tasks file for user_data
- name: Configure jenkins repo
  get_url:
    url: http://pkg.jenkins.io/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins.io.key

- name: Install latest version of Java
  yum:
    name: java
    state: latest

- name: Install the latest version of Jenkins
  yum:
    name: jenkins
    state: latest

- name: Make sure Jenkins service is running
  systemd:
    state: started
    name: jenkins
    enabled: yes
